version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: attendance_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: attendance_db
      MYSQL_USER: attendance_user
      MYSQL_PASSWORD: attendance_pass
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  attendance-app:
    container_name: attendance_app
    image: attendance_app:latest
    restart: always
    ports:
      - "3004:8000"
    depends_on:
      - mysql
    environment:
      RDS_HOSTNAME: mysql
      RDS_DB_NAME: attendance_db
      RDS_USERNAME: attendance_user
      RDS_PASSWORD: attendance_pass
      RDS_PORT: 3306
      SECRET_KEY: django-secret-key
      DEBUG: "True"
      ALLOWED_HOSTS: "*"

volumes:
  mysql_data:
